### ISSUE TITLE
lassonet

### ISSUE THREAD

**Issue by sung** [andreimargeloiu/WPFS#1]
Thanks for making this repo open/free.

While running `run_experiment.sh`, I got the following error:
```code
(WPFS) $ bash run_experiment.sh
Traceback (most recent call last):
  File "src/main.py", line 13, in <module>
    from lassonet import LassoNetClassifier
ModuleNotFoundError: No module named 'lassonet'
```

Then, I installed `lassonet` as the following:
```code
pip install lassonet
```

Still the following error from `run_experiment.sh`:
```code
(WPFS) $ bash run_experiment.sh
Traceback (most recent call last):
  File "src/main.py", line 13, in <module>
    from lassonet import LassoNetClassifier
  File "/home/ssg29/miniconda3/envs/WPFS/lib/python3.7/site-packages/lassonet/__init__.py", line 4, in <module>
    from .interfaces import (
  File "<fstring>", line 1
    (current_lambda=)
                   ^
SyntaxError: invalid syntax
```

Do you require a specific version of `lassonet`?

Thanks.

**Comment by andreimargeloiu** [comment]
Solved.
